### ISSUE TITLE
Error after running docker-compose file

### ISSUE THREAD

**Issue by keepca** [ShoGinn/adsb-docker#4]

**Comment by keepca** [comment]
Hello,
first thing firts. Thank you for the rep. :)
 Unfortunately after running the compose file.... i got this error.
Could you help me out?

Service 'dump1090' failed to build: The command '/bin/sh -c cat /etc/apk/repositories &&     echo '@edge http://nl.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories &&     echo '@testing http://nl.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories &&     cat /etc/apk/repositories &&     apk add --no-cache tini librtlsdr@testing libusb ncurses-libs' returned a non-zero code: 1

**Comment by ShoGinn** [comment]
@keepca Thanks for the interest in the repo, I just need more information about your situation.

To baseline the requirements since my readme isn't really comprehensive.

This is for docker on a raspberry pi.

I have an automated build that has all of the builds on them.

I recommend using the docker hub repository and docker-compose pull

Let me know!

**Comment by keepca** [comment]
Thank you for the answer. I tried a docker pull... But i dont use a raspberry. It is a Miniserver like a NUC. Maybe that is cause the problems i got with this compose file:

version: '3.2'

services:
  
  dump1090:
    image: shoginn/docker-ads-b-dump1090:latest
    hostname: dump1090
    ports:
      - 30002:30002
      - 30005:30005
    devices:
      - /dev:/dev
    
    
    restart: always
    #environment:
    #    - PUID=${PUID}
    #    - PGID=${PGID}
    #    - TZ=${TZ}

  
    image: shoginn/docker-ads-b-flightradar24:latest
    hostname: flightradar
    ports:
      - 8754:8754
    depends_on:
      - dump1090
    
    restart: always
    environment:
        - FR24FEED_KEY=xxx
        - FR24FEED_LATITUDE=xxx
        - FR24FEED_LONGITUDE=xxx
        - FR24FEED_ALTITUDE=10  
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}


 
  flightaware:
    image: shoginn/docker-ads-b-flightaware:latest
    ports:
      - 30105:30105
    depends_on:
      - dump1090
    
    restart: always
    environment:
        - FLIGHTAWARE_FEEDER_ID=xxxx
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}


The answer from the system was:

ERROR: for docker-ads-b_dump1090_1  Cannot start service dump1090: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:70: creating device nodes caused \\\"open /var/lib/docker/overlay2/ae466b3de8f8f6c195670478e25290c3a9ef2ba975a25163274c5365c9d0e823/merged/dev/pts/0: permission denied\\\"\"": unknown

ERROR: for dump1090  Cannot start service dump1090: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:70: creating device nodes caused \\\"open /var/lib/docker/overlay2/ae466b3de8f8f6c195670478e25290c3a9ef2ba975a25163274c5365c9d0e823/merged/dev/pts/0: permission denied\\\"\"": unknown

**Comment by ShoGinn** [comment]
Nope the problem is that it is compiling for arm processor not i386.

I plan on updating this to work on both arm and i386 (as im probably going to migrate my adsb to my home server)

Star the repo for updates, and hopefully shortly I can get it done.

**Comment by keepca** [comment]
Thank you :)
