### ISSUE TITLE
Derived work license

### ISSUE THREAD

**Issue by TheBiggerGuy** [ShoGinn/adsb-docker#5]
Hi,
I am the owner of https://github.com/TheBiggerGuy/docker-ads-b and it appears this project is heavily derived from it. The original project is under the MIT licence and I invite people to fork and generally do what they want with it. However the only requirement is that you maintain the licence text.

> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.
> _https://github.com/TheBiggerGuy/docker-ads-b/blob/latest/LICENSE_

Please could you correct me on my assumption that this project is derivative or include the required LICENSE file.

Please feel free to contact me for more information or questions.

**Comment by ShoGinn** [comment]
Very fair! I forgot to add it to this one ;)

https://github.com/ShoGinn/docker-ads-b/commit/41382284f0f7affd65f9266e3776608f5ac7148c
